-- Calculate the total sales amount (based on product price and quantity sold) for each month in the year 2022.
-- The result should have two columns: Month (formatted as YYYY-MM) and TotalSalesAmount
-- Order the result by month in ascending order.
